bugfix/1-3 メールアドレスの重複処理
tatsu2323/ex-emp-management-bugfix pull request #4
Opened 2024-11-22 08:11 UTC by tatsu2323

2024-11-22 08:13 UTC, tatsu2323 commented
コメントなし送ってしまいました。
メールアドレスの重複処理を追加しました。
重複していれば、エラーメッセージが表示されて管理者登録画面に遷移します。

2024-11-22 08:20 UTC, mariyamasan approved these changes

2024-11-22 08:20 UTC, mariyamasan commented on src/main/java/com/example/form/InsertAdministratorForm.java
> +	@NotBlank (message = "メールアドレスは入力してください")
面白い文章ですね（笑）

2024-11-22 08:21 UTC, mariyamasan commented
OKです！コンフリクト起こしているのでそれだけ訂正していただければマージします！

2024-11-22 08:33 UTC, tatsu2323 commented on src/main/java/com/example/form/InsertAdministratorForm.java
> +	@NotBlank (message = "メールアドレスは入力してください")
恥ずかしいです笑
コンフリクト解消できてますかね？
GItが苦手でして、、

2024-11-22 08:37 UTC, mariyamasan commented on src/main/java/com/example/form/InsertAdministratorForm.java
> +	@NotBlank (message = "メールアドレスは入力してください")
@tatsu2323 
コンフリクト自体は発生していないようですが、恐らく ====== だけを削除した 状態かと思われます。
その結果、意図していない実装（insert メソッドが2つ存在する） 状態になっているようです。

現在のコードを再度修正していただき、改めてプルリクエストを送っていただければ問題なく進められるかと思います。
よろしくお願いします！

2024-11-25 06:55 UTC, mariyamasan requested changes

2024-11-25 06:55 UTC, mariyamasan commented on src/main/java/com/example/controller/AdministratorController.java
>  	public String insert(InsertAdministratorForm form) {
@tatsu2323 
メソッドが同じ名前だと可読性がとてもさがるので意図に沿って変えたほうがいいと思います！

あとこのメソッドで行っている処理は下記のようにまとめれるので参考にしてみてください。
```java

@PostMapping("/insert")
	public String insert(@Validated InsertAdministratorForm form, BindingResult result, Model model) {
		// メールアドレスの重複があれば入力場面に遷移
		Administrator administrator = new Administrator();
		administrator = administratorService.findByMailAddress(form.getMailAddress());
		if (administrator != null) {
			model.addAttribute("duplicationMessage", "Mailアドレスが重複しています");
			return "administrator/insert";
		} else if (result.hasErrors()) {
			// 入力項目にエラーがあれば入力画面に遷移する
			return "administrator/insert";
		}
		administrator = new Administrator();
		BeanUtils.copyProperties(form, administrator);
		administratorService.insert(administrator);

		return "redirect:/";
	}
```

2024-11-25 06:59 UTC, merged